
# .github/workflows/CI.yml

name: CI
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64

    steps:
      # 1. Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up the specified Julia version
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # 3. Cache dependencies to speed up builds
      - name: Cache artifacts
        uses: julia-actions/cache@v2

      # 4. Install package dependencies
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      # 5. Run the tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
