
name: Tests
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64

    steps:
      # 1. Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up the specified Julia version
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # 3. Cache dependencies to speed up builds
      - name: Cache artifacts
        uses: julia-actions/cache@v2

      # 4.1. Instantiate  
      - name: Develop local sub-projects
        shell: julia --project -e '{0}'
        run: |
          using Pkg;
          Pkg.develop([
           PackageSpec(path="."), 
           PackageSpec(path="Homework1"), 
           PackageSpec(path="Homework2"), 
           PackageSpec(path="Homework3")
          ])
          Pkg.instantiate();

      # 4.2. Build package (Installs main AND test dependencies)
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      # 5. Run the tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
