
name: Tests
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64

    steps:
      # 1. Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up the specified Julia version
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # 3. Cache dependencies to speed up builds
      - name: Cache artifacts
        uses: julia-actions/cache@v2

      # 4. Install dependencies for main project AND for the test environment
      - name: Install dependencies
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate(".")
          Pkg.develop([
            PackageSpec(path="Homework1"), 
            PackageSpec(path="Homework2"), 
            PackageSpec(path="Homework3")
          ])
          Pkg.instantiate()
          Pkg.activate("./test")
          Pkg.add("Test")
          Pkg.develop([
              PackageSpec(path="."),
              PackageSpec(path="Homework1"),
              PackageSpec(path="Homework2"),
              PackageSpec(path="Homework3")
          ])
          Pkg.instantiate()
          Pkg.activate(".")

      # 5. Run the tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
